# Kompilē ar make
#palaiž ar ./bomberman_server
# Lai iztīrītu kompilētos failus, izmanto make clean

CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -O2
LDFLAGS =
SRC_DIR = src
BUILD_DIR = build
TARGET = bomberman_server

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ = $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRC))

all: $(TARGET)

$(TARGET): $(OBJ)
    $(CC) $(OBJ) -o $(TARGET) $(LDFLAGS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
    mkdir -p $(BUILD_DIR)
    $(CC) $(CFLAGS) -c $< -o $@

clean:
    rm -rf $(BUILD_DIR) $(TARGET)

.PHONY: all clean
